apiVersion: v1
kind: Service
metadata:
  name: myapp-sc
  labels:
    app: myapp-service
    type: frontend
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      NodePort: 30008
  selector:
    metchLables:
      app: myapp
      type: frontend
