apiVersion: v1
kind: Pod
metadata:
  name: security-app
spec:
  restartPolicy: OnFailure
  containers:
    - name: linix
      image: linux
      securityContext:
        runAsUser: 1000
        capabilities:
           add: ["MAC_ADMIN"]
