apiVersion: v1
kind: Pod
metadata:
  name: taint-pod
spec:
  containers:
    - name: nginx
      image: nginx
  tolerations:
    - effect: NoSchedule 
      key: app
      operator: Equal
      value: dev