apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  restartPolicy: OnFailure
  containers:
    - name: mysql-db-container3
      image: mysql:8.1.0
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_USER
          value: root
        - name: MYSQL_ROOT_PASSWORD
          value:
