apiVersion: v1
kind: Pod
metadata:
  name: app-config-pod
spec:
  restartPolicy: OnFailure
  containers:
    - name: mysql
      image: mysql:8.1.0
      envFrom:
        - configMapRef:
            name: app-config
