apiVersion: v1
kind: Pod
metadata:
  name: app-config-pod
spec:
  restartPolicy: Never
  containers:
    - name: mysql
      image: mysql:8.1.0
      envFrom:
        - secretRef:
            name: app-config