apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  capacity:
    storage : 10Mi
  persistentVolumeReclaimPolicy: Delete
  hostPath: 
    path: /c/Users/PARTH/OneDrive/Desktop/