apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: new
spec:
  restartPolicy: Never
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: my-pvc
  containers:
    - image: ubuntu:23.10
      name: ubuntu
      command: ["/bin/sh", "-c"]
      args: 
        - echo 'hello' > /home/t.txt
      volumeMounts:
        - mountPath: /home
          name: data-volume