apiVersion: v1
kind: Pod
metadata:
  name: new
spec:
  volumes:
    - name: data-volume
      hostPath:
        path: /c/Users/PARTH/OneDrive/Desktop/New_folder/data
        type: Directory
  containers:
    - image: ubuntu:23.10
      name: ubuntu
      command: ["/bin/sh", "-c"]
      args: 
        - echo 'hello' > /c/Users/PARTH/OneDrive/Desktop/New_folder/data/opt/t.txt
      volumeMounts:
        - mountPath: /c/Users/PARTH/OneDrive/Desktop/New_folder/data/opt
          name: data-volume
  